version: "2.1"

services:

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather-base:
    image: ehealthafrica/gather:${GATHER_VERSION:-latest}
    stdin_open: true
    tty: true
    environment:
      CSRF_COOKIE_DOMAIN: gather.local
      # Uncomment these lines to enable single sign on if you use CAS
      # CAS_SERVER_URL: https://your.cas.server
      # HOSTNAME: gather.local

      DJANGO_SECRET_KEY: ${GATHER_DJANGO_SECRET_KEY}

      ADMIN_USERNAME: ${GATHER_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${GATHER_ADMIN_PASSWORD}

      AETHER_KERNEL_TOKEN: ${KERNEL_ADMIN_TOKEN}
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9000
      AETHER_KERNEL_URL_ASSETS: http://kernel.aether.local

      AETHER_MODULES: "kernel,odk,"

      AETHER_ODK_TOKEN: ${ODK_ADMIN_TOKEN}
      AETHER_ODK_URL: http://odk:8002
      AETHER_ODK_URL_TEST: http://odk-test:9002
      AETHER_ODK_URL_ASSETS: http://odk.aether.local

      DB_NAME: gather
      PGHOST: db # This matches the DB service name
      PGPASSWORD: ${GATHER_DB_PASSWORD}
      PGPORT: 5432
      PGUSER: postgres

      EXPORT_MAX_ROWS_SIZE: 100000

      WEB_SERVER_PORT: 8005
    volumes:
      # static folder used by nginx
      - ./aether-bootstrap/.persistent_data/static/gather:/var/www/static
      # backup folder
      - ./aether-bootstrap/.persistent_data/backups/gather:/backups
    ports:
      - "8005:8005"
    command: start
